# .github/workflows/helfer_bot.yml

name: GitHub Helfer-Bot Suchlauf

on:
  schedule:
    # Führt das Skript zu jeder vollen Stunde aus
    - cron: '0 * * * *'
  workflow_dispatch: # Erlaubt manuelles Starten

jobs:
  run-search:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: pip install requests

      - name: Helfer-Bot Skript ausführen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python helfer_bot.py
